/* eslint-disable */
module.exports = {
  port: 8888,
  falcon: function() {
    console.log('==========================================');
    console.log("WWWNdsyWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWysdNWWW");
    console.log("WWWWWWh/`:ohNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNho:`/hWWWWWW");
    console.log("WWWWWWWWWo.  ./sdNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNds/.  .oWWWWWWWWW");
    console.log("WWWWWWWWWWNy:    `-+ydWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWdy+-`    :yNWWWWWWWWWW");
    console.log("WWWWWWWdohWWWW+`      `:+yWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWy+:`      `+WWWWhodWWWWWWW");
    console.log("WWWWWWWWN+-sNWWNy:        `.:ohWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWho:.`        :yNWWNs-+NWWWWWWWW");
    console.log("WWWWWWWWWWh.`+dWWWd+`          `./hWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWh/.`          `+dWWWd+`.hWWWWWWWWWW");
    console.log("WWWWWWWWWWWN+ `:yNWWNs-           `yWWWWWWWWWWWWWWWWWWWWWWWWWWWWy`           -sNWWNy:` +NWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWh.  .oWWWNd+`          sWWWWWWWWWWWWWWWWWWWWWWWWWWs          `+dNWWWo.  .hWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWN+   `/hWWWWs-         +WWWWWWWWWWWWWWWWWWWWWWWW+         -sWWWWh/`   +NWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWh.   `-yNWWNh/        /NWWWWWWWWWWWWWWWWWWWWN/        /hNWWNy-`   .hWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWNo-    .oWWWWs        :NWWWWWWWWWWWWWWWWWWN:        sWWWWo.    -oNWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWNdo-   .hWWWy`       -WWWWWWWWWWWWWWWWWW-       `yWWWh.   -odNWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWNNNdo- `yWWWh.       -hyNWWWWWWWWWWWhy-       .hWWWy` -odNNNWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWNdyhNNdo:sWWWW-       `./NWWWWWWWWWo.`       -WWWWs:odNNhydNWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWNh+/yWNdNWWWW:      sN :WWWWWWWN+ dh.     :NWWWNdNWy/+hNWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWNh/.:sdNWWWN/   `yWWN -dWWWWN/ WWWW-   /NWWWNds:./hNWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWd/``-oWWWW+ .hWWWWW .hWWW- NWWWWW: +WWWWo-``/dWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWd+` .dWN/.dWWWWWWW  yd. NWWWWWWN -WWd. `+dWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo..y -WWWWWWWWWW ` oWWWWWWWWWN+ s..oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW. /NWWWWWWWWWW  . +NWWWWWWWWWW `:WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW .+NWWWWWWWWWWs hW /NWWWWWWWWWWy sWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW .oWWWWWWWWWWN+ dWWN :WWWWWWWWWWWh oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW .yWWWWWWWWWWN/ WWWWWN -dWWWWWWWWWWW +NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW .hWWWWWWWWWWW- NWWWWWWW .hWWWWWWWWWWW  NWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWN .dWWWWWWWWWWd- NWWWWWWWWW .yWWWWWWWWWWN -WWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWN -WNNNNNNNNNNh +NNNNNNNNNNNN `sNNNNNNNNNNN .wWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWW.              .               .             .wWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWhNNNNNNhNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd-dWWWWWWo/WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNo`-WWWddWWW .yWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd-  sWWW/+WWW/  /NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNo`  `NWWN``WWWd   .hWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN-    +WWWs  hWWW.    +WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWs`   WWWW.  :WWWs   .dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW- :WWWh    NWWN` /NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN+hWWW/    sWWW+sWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN     .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
    console.log(`WRANNAWAN on ${this.port}.`);
    console.log('==========================================');
  }
}
